spring:
  application:
    name: test-db
  profiles: 
    active: default

---

spring:
  config: 
    activate: 
      on-profile: "default"

  datasource:
    url: jdbc:mysql://localhost:3306/test_mysql?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&autoReconnection=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    hikari:
      auto-commit: false

mybatis:
  type-aliases-package: com.example.multi.demo.**.model
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true